// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tgcqwfnufqqtqbpjkuem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRnY3F3Zm51ZnFxdHFicGprdWVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5Njc1NjAsImV4cCI6MjA1NzU0MzU2MH0.f4hVPSBjDxaHA-HeL2hwCJTvIOOTIc3CGcXJpB59WKE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);